server:
  port: 8080   # HTTP (Tomcat) port

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alipay?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  #rabbitmq:
    #host: 127.0.0.1
    #port: 5672
    #username: guest
    #password: guest
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
logging:
  level:
    com.demo.web.dao: debug